POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYSIsImlkIjoiNjI4MmFjMjhmNGU3NTI1ZTlkNDQ5ZTc1IiwiaWF0IjoxNjUyNzM1NTUwLCJleHAiOjE2NTI3MzkxNTB9.a352yzTvYKEyIGKUMu-s3QQnr4bltXPTZimeK4b_Cn0

{
  "title": "2nd Blog with userId and token",
  "author": "Blogger",
  "url": "www.blogger-blogs/p2.com",
  "likes": 0,
  "userId": "6282ac28f4e7525e9d449e75"
}