POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYSIsImlkIjoiNjI4MmFjMjhmNGU3NTI1ZTlkNDQ5ZTc1IiwiaWF0IjoxNjUyODA4Mzc1LCJleHAiOjE2NTI4MTE5NzV9.6SfHAG36iJVyQ_F92LzeA6UvzPIDnwt2BATK50T8cTs

{
  "title": "blog for userextractor",
  "author": "Blogger",
  "url": "www.blogger-blogs/p2.com",
  "likes": 0,
  "userId": "6282ac28f4e7525e9d449e75"
}